site_name: Curren's Notes

repo_url: https://github.com/CurrenWong/Mkdoc/

site_author: Curren

site_description: Curren's Notes

theme: 
  name: material
  highlightjs: false
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra_javascript:
  - js/katex.min.js
  - js/mathtex-script-type.min.js
  - js/copy-tex.min.js
  - js/auto-render.min.js
#   - js/extra.js # 渲染未被mathJax捕捉的公式

extra_css:
  - css/katex.min.css
  - css/copy-tex.min.css
  - css/extra.css

markdown_extensions:
  - mdx_math:
        add_preview: false
        enable_dollar_delimiter: true
  - toc:
        permalink: true
        marker: "[TOC]"
  - sane_lists
  - meta
  - wikilinks
  - admonition
  - codehilite:
        linenums: true
        linenums: true

