site_name: Curren's Notes

repo_url: https://github.com/CurrenWong/Mkdoc/

repo_name: 'currenwong/Mkdoc'

site_author: Curren

site_description: Curren's Notes

theme: 
  name: material
  custom_dir: overrides
  palette: # 颜色
    primary: 'indigo'
    accent: 'deep orange'
  icon: # 图标
    logo: 'bootstrap/star'
  features: # 是否将一层目录显示为上方的tab
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    # remain visible when scrolling down
    # - navigation.tabs.sticky
    # self show on toc
    - navigation.indexes
    # toc follow content in link
    # - toc.follow
    - navigation.top
    # - navigation.sections
  language: 'en' # 语言

extra_javascript:
  - js/katex.min.js
  - js/mathtex-script-type.min.js
  - js/copy-tex.min.js
  - js/auto-render.min.js
  - js/jquery-3.4.1.min.js # 定制jQuery函数
  - js/d3.min.js
  - js/d3-flextree.js
  - js/view.mindmap.js
  - js/emoji.min.js # 显示emoji
  - js/mermaid.min.js # Mermaid UML
  - js/highlight.pack.js # 代码高亮
  # 访问量统计
  # - https://cdn1.lncld.net/static/js/av-min-1.5.0.js
  # - https://jerryz.sgp1.cdn.digitaloceanspaces.com/lib/hit-kounter/hit-kounter-lc-0.3.0.js
  - js/readingtime.js # 显示阅读时间
  - js/extra.js # 渲染未被mathJax捕捉的公式，渲染思维导图
  
extra_css:
  - css/katex.min.css
  - css/copy-tex.min.css
  - css/view.mindmap.css
  # - css/highlight-default.css # 代码高亮主题
  - css/atom-one-dark-reasonable.css # 代码高亮主题
  - css/font-awesome-all.min.css # font-awesome 图标
  - css/emoji.css # 显示emoji
  - css/extra.css

markdown_extensions:
  - tables
  - mdx_math:
        add_preview: false
        enable_dollar_delimiter: true
  - toc:
        permalink: "#" # 设置标题链接的标志
        marker: "[TOC]"
        toc_depth: 4
        anchorlink: true
        baselevel: 1
  # Material
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  # - sane_lists
  # - meta
  # - wikilinks
  # - admonition
  # highlight
  - pymdownx.highlight:
      use_pygments: false
      anchor_linenums: false
      linenums: false
  # - pymdownx.inlinehilite
  # - pymdownx.snippets
  # - pymdownx.superfences


plugins:
  # - search
  - build_plantuml:
      render: "server" # or "local" for local rendering
      bin_path: "/usr/local/bin/plantuml" # ignored when render: server
      server: "http://www.plantuml.com/plantuml" # offical plantuml server
      output_format: "svg" # or "png"
      diagram_root: "docs/diagrams" # should reside under docs_dir
      output_folder: "out"
      input_folder: "src"

