site_name: Curren's Notes

repo_url: https://github.com/CurrenWong/Mkdoc/

site_author: Curren

site_description: Curren's Notes

theme: 
  name: material
  highlightjs: false
  shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s

extra_javascript:
  - js/katex.min.js
  - js/mathtex-script-type.min.js
  - js/copy-tex.min.js
  - js/auto-render.min.js
  - js/jquery-3.4.1.min.js # 定制jQuery函数
  - js/d3.min.js
  - js/d3-flextree.js
  - js/view.mindmap.js
  - js/highlight.pack.js # 代码高亮
  - js/extra.js # 渲染未被mathJax捕捉的公式，渲染思维导图

extra_css:
  - css/katex.min.css
  - css/copy-tex.min.css
  - css/view.mindmap.css
  - css/highlight-default.css # 代码高亮主题
  - css/extra.css

markdown_extensions:
  - mdx_math:
        add_preview: false
        enable_dollar_delimiter: true
  - toc:
        permalink: "#" # 设置标题链接的标志
        marker: "[TOC]"
        toc_depth: 4
        anchorlink: true
        baselevel: 1
        
  - sane_lists
  - meta
  - wikilinks
  - admonition
